---
title: "ASSIGNMENT 2"
author: "MADHUKAR"
date: "2/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(caret)
library(class)
```

TASK 1

```{r}
UniversalBank <- read.csv("UniversalBank.csv", sep = ',', fill = F, strip.white = T)

```




```{r}
colnames(UniversalBank)<-c('ID', 'Age','Experience','Income','ZIP Code','Family','CCAvg','Education','Mortgage','Personal.Loan','Securities.Account','CD.Account','Online','CreditCard')
```
```{r}
summary(UniversalBank)
```

```{r}
UniversalBank$ID <-NULL
UniversalBank$`ZIP Code` <-NULL
```

```{r}
`UniversalBank_dummy=as.data.frame(predict(dummies,newdata = UniversalBank)
```


```{r}
``

head(UniversalBank_dummy)
```

```{r}
Norm_model <- preProcess(UniversalBank_dummy, method = c("center", "scale"))
```

```{r}
UniversalBank_norm=predict(Norm_model,UniversalBank_dummy)
```

```{r}
summary(UniversalBank_norm)
```

```{r}
UniversalBank_norm$Personal.Loan = UniversalBank$Personal.Loan

```

```{r}
Train_Index = createDataPartition(UniversalBank$Personal.Loan,p=0.6, list=FALSE)
Train.df=UniversalBank_norm[Train_Index,]
Validation.df=UniversalBank_norm[-Train_Index,]
```

```{r}
To_Predict=data.frame(Age = 40, Experience = 10, Income = 84, Family = 2, CCAvg = 2, Education= 1,Mortgage = 0, Securities.Account = 0, CD.Account = 0, Online = 1,CreditCard = 1)
```


```{r}
print(To_Predict)
To_Predict_norm<-predict(Norm_model,To_Predict)
```

```{r}
print(To_Predict_norm)
```

```{r}
Prediction <-knn(train=Train.df[,1:7,9:12], 
                 test=To_Predict_norm[,1:7,9:12],
                 cl=Train.df$Personal.Loan,
                 k=1)
```

```{r}
print(Prediction)
```

TASK 2:
```{r}
fitControl <- trainControl(method = "repeatedcv",
                           number = 3,
                           repeats = 2)
```

```{r}
searchGrid=expand.grid(k = 1:10)
```

```{r}
Knn.model=train(Personal.Loan~., 
                data=Train.df,
                method='knn',
                tuneGrid=searchGrid,
                trControl = fitControl,)
Knn.model
```

TASK 3
```{r}
predictions<-predict(Knn.model,Validation.df)
confusionMatrix(predictions,Validation.df$Personal.Loan)
```

TASK 4
```{r}
To_Predict=data.frame(Age=40,Experience = 10, Income = 84, Family = 2, CCAvg = 2, Education = 0, Mortgage = 0, Securities.Account = 0, CD.Account = 0, Online = 1, CreditCard = 1)

```
```{r}
To_Predict_norm=predict(Norm_model,To_Predict)
predict(Knn.model,To_Predict_norm)
```


















